const BLACK = "#000";
const WHITE = "#fff";
const RICHBLACK = "#002233";
const RICHBLACK_RBG = "0,34,51";
const VDEP_BLUE = "#00AEED";
const VDEP_SECONDARY_BLUE = "0183B7";
const VDEP_GREEN = "7CC04E";

export const COLOR = {
  BLACK,
  WHITE,
  RICHBLACK,
  RICHBLACK_RBG,
  VDEP_BLUE,
  VDEP_SECONDARY_BLUE,
  VDEP_GREEN,
  RICHBLACK_80: `rgba(${RICHBLACK_RBG},.8)`,
};
